name: Set Node Version

on: [ workflow_call ]

env:
  NODE_VERSION: 16

jobs:
  installing_node:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Check Node Version
        run: node --version