# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish CI


on:
  workflow_dispatch:
    inputs:
      als-version:
        description: 'ALS node client version to install (f.e.: 1.2.3-SNAPSHOT.45)'
        required: true
        default: 'latest' 
        type: string
    
env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  install_npm:
    uses: ./.github/workflows/install_npm.yml

  build:
    runs-on: macos-latest
    needs: [ install_npm ]

    steps:
    - uses: actions/checkout@v3

    - name: Set package version to latest
      run: bash extension-version.sh
    - run: npm i
    - run: npm install -g @vscode/vsce
    - name: Install ALS node client ${{ github.event.inputs.als-version }}
      run: npm install @aml-org/als-node-client@${{ github.event.inputs.als-version }}

    - name: Check custom dependencies installed
      run: npm ls | grep @aml-org
    - name: Set package version to latest
      run: bash extension-version.sh
    - run: npm run build --if-present
    - run: npm run test
    - run: vsce publish --no-git-tag-version patch

    - name: Notify slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
            {
              "project": "als-vscode :vscode:",
              "result": "Publication finished successfully: https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.aml-vscode",
              "version": " - "
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}