name: Notify Slack Channel

on: [ workflow_call ]

env:
  CHANNEL_NAME: "als-extension-bot"
  REF_SLACK_VERSION: v1.18.0

jobs:
  notify_slack_channel:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Notifying
      - name: "Notifying to Slack Channel: ${{ env.CHANNEL_NAME }}"
        id: slack
        uses: slackapi/slack-github-action@${{ env.REF_SLACK_VERSION }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "project": "als-vscode :vscode:",
              "result": "Publication finished successfully: https://marketplace.visualstudio.com/items?itemName=MuleSoftInc.aml-vscode",
              "version": " - "
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}