# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish CI

on:
  push:
    branches: [ master ]
    
env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}

jobs:
  install_npm:
    uses: ./.github/workflows/install_npm.yml

  build:
    runs-on: macos-latest
    needs: [ install_npm ]

    steps:
    - uses: actions/checkout@v3

    - run: npm install -g vsce
    - run: npm ci
    - name: Set package version to latest
      run: bash extension-version.sh
    - run: npm run build --if-present
    - run: npm run test
    - run: vsce publish --no-git-tag-version patch

  notify_slack:
    # Some condition may be added no not notify every manual test
    uses: ./.github/workflows/notify_slack.yml
    needs: [ build ]