# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ master ]
    
env:
  ALS_NODE_CLIENT_DEPENDENCY_NAME: "@aml-org/als-node-client"

jobs:
  install_npm:
    uses: ./.github/workflows/install_npm.yml

  build:
    runs-on: windows-latest
    needs: [ install_npm ]

    steps:
    - uses: actions/checkout@v3

    - name: Install ALS Node Client dependency
      run: npm i ${{ ALS_NODE_CLIENT_DEPENDENCY_NAME }}
    - run: npm ci
    - run: npm run build --if-present
    - uses: Check custom dependencies installed
      run: npm ls | grep @aml-org
    - id: test
      run: npm run test
      continue-on-error: true

  notify_slack:
    # Some condition may be added to not notify every test
    uses: ./.github/workflows/notify_slack.yml
    needs: [ build ]
