# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manual Test CI

on:
  workflow_dispatch:
    inputs:
      als-version:
        description: 'ALS node client version to install (f.e.: 1.2.3-SNAPSHOT.45)'
        required: true
        default: 'latest' 
        type: string

jobs:
  install_npm:
    uses: ./.github/workflows/install_npm.yml

  build:
    runs-on: windows-latest
    needs: [ install_npm ]

    steps:
    - uses: actions/checkout@v3

    - run: npm ci
    - name: Install ALS node client ${{ github.event.inputs.als-version }}
      run: npm install @aml-org/als-node-client@${{ github.event.inputs.als-version }}
    - uses: Check custom dependencies installed
      run: npm ls | grep @aml-org
    - run: npm run build --if-present
    - id: test
      run: npm run test
      continue-on-error: true

  notify_slack:
    # Some condition may be added to not notify every manual test
      uses: ./.github/workflows/notify_slack.yml
      needs: [ build ]